abundance_samples:
- Vf
- Bs
anvi_env: source activate sn_anvio
assemblers:
- megahit
- metaspades
binning_samples:
- Vf
- Bs
env: source activate snakemake_assemble
humann2_env: source activate humann2
kraken_env: source activate kraken
mapping_assembler: metaspades
metaphlan_env: source activate humann2
params:
  atropos: ' -a GATCGGAAGAGCACACGTCTGAACTCCAGTCAC -A GATCGGAAGAGCGTCGTGTAGGGAAAGGAGTGT
    -q 15 --minimum-length 100 --pair-filter any'
  cram: ''
  humann2:
    humann2_aa_db: 'humann2_aa_db: /home/jgsanders/ref_data/humann2/uniref'
    humann2_nt_db: /home/jgsanders/ref_data/humann2/chocophlan
    metaphlan_dir: /home/jgsanders/share/metaphlan2
    norms:
    - cpm
    - relab
    other: ''
  kraken:
    kraken_db: /home/qiz173/Databases/Kraken/stdb
  maxbin: -plotmarker
  metaphlan:
    metaphlan_dir: /home/jgsanders/git_sw/metaphlan2
  shogun: --utree_indx /home/qiz173/Databases/SHOGUN/annotated/utree/stdb.ctr
  skewer: -x ./adapters/HyperPlus.fa -n -l 100 -m any -q 15
resources:
  centrifuge_base: /home/jgsanders/miniconda/envs/anvio2/centrifuge
  centrifuge_models: /home/jgsanders/miniconda/envs/anvio2/centrifuge/b+h+v/b+h+v
samples:
  Bs:
    filter_db: /home/jgsanders/ref_data/genomes/Homo_sapiens_Bowtie2_v0.1/Homo_sapiens
    forward:
    - ./example/reads/Bs_S106_L001_R1_001.fastq.gz
    - ./example/reads/Bs_S106_L002_R1_001.fastq.gz
    reverse:
    - ./example/reads/Bs_S106_L001_R2_001.fastq.gz
    - ./example/reads/Bs_S106_L002_R2_001.fastq.gz
  Vf:
    filter_db: /home/jgsanders/ref_data/genomes/Homo_sapiens_Bowtie2_v0.1/Homo_sapiens
    forward:
    - ./example/reads/Vf_S104_L001_R1_001.fastq.gz
    - ./example/reads/Vf_S104_L002_R1_001.fastq.gz
    reverse:
    - ./example/reads/Vf_S104_L001_R2_001.fastq.gz
    - ./example/reads/Vf_S104_L002_R2_001.fastq.gz
shogun_env: source activate shogun
software:
  mash: /home/jgsanders/git_sw/git_bin/mash
  seqtk: seqtk
  snakemake_folder: /home/jgsanders/git_sw/snakemake_assemble
tmp_dir_root: /localscratch
trimmer: atropos
