
tmp_dir_root: ./

env: source activate snakemake_assemble
anvi_env: source activate sn_anvio

software:
  snakemake_folder: ./

params:
  skewer: -x ./adapters/HyperPlus.fa -n -l 100 -m any -q 15
  cram:
  maxbin: -plotmarker

resources:
  centrifuge_base: /home/jgsanders/miniconda/envs/anvio2/centrifuge
  centrifuge_models: /home/jgsanders/miniconda/envs/anvio2/centrifuge/b+h+v/b+h+v

binning_samples:
  - sample1
  - sample2

abundance_samples:
  - sample1
  - sample2

assemblers:
  - megahit
  - metaspades

mapping_assembler: metaspades

samples:
  sample1:
    filter_db: 
    forward: 
    - example/reads/Bs_L001_R1.fastq.gz
    - example/reads/Bs_L002_R1.fastq.gz
    reverse:
    - example/reads/Bs_L001_R2.fastq.gz
    - example/reads/Bs_L002_R2.fastq.gz
  sample2:
    filter_db: 
    forward: 
    - example/reads/Vf_L001_R1.fastq.gz
    - example/reads/Vf_L002_R1.fastq.gz
    reverse:
    - example/reads/Vf_L001_R2.fastq.gz
    - example/reads/Vf_L002_R2.fastq.gz